### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by eamanu** [ECSIM/opem#207]
Hi!

@NGC2023 Is working in package opem in Debian.  I can note that develop branch is working with py3.12. But apply the patch https://github.com/ECSIM/opem/pull/203 to version 1.3 is not an easy task.

So, our option is deactivate tests for Python3.12 but it is not so good. It would be possible generate a new release release of opem soon?

Thanks!
Cheers!

**Comment by sepandhaghighi** [comment]
@eamanu Hi ✋ 
Yeah, we will be releasing a new version of **OPEM** (v1.4) within the next **2-3 weeks**.
