### ISSUE TITLE
Do not use `except Exception`

### ISSUE THREAD

**Issue by nnadeau** [ECSIM/opem#40]
- E.g.,: https://github.com/ECSIM/opem/blob/d9748c65ff00ff9f6b730420dc7bb6cad8bc2fca/opem/Static/Amphlett.py#L22-L25
- See the following links for why this is considered poor coding practice:
    - https://stackoverflow.com/questions/10594113/bad-idea-to-catch-all-exceptions-in-python
    - https://stackoverflow.com/questions/2416316/why-is-the-catchexception-almost-always-a-bad-idea
    - https://softwareengineering.stackexchange.com/questions/164256/is-catching-general-exceptions-really-a-bad-thing
- If this is really necessary, the reasoning should be commented.

**Comment by sepandhaghighi** [comment]
Hi @nnadeau 

It's true, using of general exception is not a good point but in OPEM we don't want to handle different exceptions in different ways so I think it's oky.

Thanks

**Comment by sepandhaghighi** [comment]
@katyhuff 

As I mentioned before, in OPEM we don't want to handle different exceptions in different ways, and there is a single response to all of exceptions so I think general exception is not a problem in this case.

Thanks

**Comment by nnadeau** [comment]
@sepandhaghighi, unfortunately I disagree. The vast majority of the package's functions have a `try-except` at their returns, catching everything and anything, even for functions that are simply multiplying several floats...

E.g., 
https://github.com/ECSIM/opem/blob/d9748c65ff00ff9f6b730420dc7bb6cad8bc2fca/opem/Static/Amphlett.py#L11-L25

The function is a simple/trivial: `float` * ((`int` * `const float`) - `float`)

There should literally never be an exception...
