### ISSUE TITLE
Plagiarism of `PEM.md`

### ISSUE THREAD

**Issue by nnadeau** [ECSIM/opem#47]
In its current form, `PEM.md` is plagiarized, word-for-word, from http://physics.oregonstate.edu/~hetheriw/energy/topics/doc/electrochemistry/fc/basic/The_Polymer_Electrolyte_Fuel_Cell.htm

**Comment by nnadeau** [comment]
Unfortunately, https://github.com/ECSIM/opem/issues/47 appears to be a case of plagiarism in the documentation. Considering that the entirety of `PEM.md` is copied, permission should be granted from the original author. Otherwise the reader should be referred directly to the original source.

**Comment by katyhuff** [comment]
@kasraaskari : I believe that @nnadeau was not suggesting that you only add the reference to the original source. Rather, I think the current state is still plaigarism as there is no permission from the original author for you to copy it. Indeed, I recommend that you *remove* all text that was plagiarized *and* direct the reader to the original source *instead* of including the copied text.

**Comment by katyhuff** [comment]
(cc @sepandhaghighi )
