### ISSUE TITLE
Apply best practices to testing

### ISSUE THREAD

**Issue by nnadeau** [ECSIM/opem#50]
- Currently, all testing is consolidated in `opem/opem/test.py` as a pseudo-doctest file
  - This is actually improper usage of doctests
  - It is hard to understand how and what is being tested
- If doctests are to be used, they should be implemented in the docstrings
- Otherwise, testing should use a proper framework 
- See http://docs.python-guide.org/en/latest/writing/tests/ for best practices

**Comment by sepandhaghighi** [comment]
Hi @nnadeau 

I used `doctest.testfile`  method because of `.coverage` file merge problem in docstring mode, and we have some output style test in OPEM that I think doctest is better than `pytest` and `unittest` in this case.

Thanks

**Comment by nnadeau** [comment]
Can you please provide a more detailed description of the `merge problem` and `output style test`?

**Comment by sepandhaghighi** [comment]
@nnadeau 

Merge problem : each function tests in `docstring` mode create one `.coverage` file and this file overwrite by next.

Output style test : some functions output style in console

Thanks
