### ISSUE TITLE
Why not use SciPy or NumPy?

### ISSUE THREAD

**Issue by nnadeau** [ECSIM/opem#53]
[SciPy](https://github.com/scipy/scipy) and [NumPy](https://github.com/numpy/numpy/) are considered the gold-standard and foundations of the Python scientific stack. Several functions can easily be replaced by these well-documented and tested packages.

E.g.,
https://github.com/ECSIM/opem/blob/41ed7e45c53c05bc5517ab005cb936b71c7e8e7a/opem/Functions.py#L14-L34

Can easily be replaced by [`numpy.trapz`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.trapz.html) or [`scipy.integrate.trapz`](https://docs.scipy.org/doc/scipy-0.10.1/reference/generated/scipy.integrate.trapz.html)

**Comment by sepandhaghighi** [comment]
@nnadeau 

Yes is true, but these pacakges increase `OPEM` exe file in freeze style (by `Pyinstaller`)  about 300 MB, so we decided to implement these 2 functions by hands (`integrate` and `simple linear regression`)

Thanks
